### ISSUE TITLE
Does not work with HDT 1.6.1

### ISSUE THREAD

**Issue by SimonDeLaus** [CookieCompiler/Hearthstone-Collection-Tracker#1]
This error I get:

Make sure you are using the latest version of the Plugin and HDT.
System.Exception: File with your collection information is corrupted. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Collection_Tracker.SetCardsManager.<>c__DisplayClass2_0.<LoadSetsInfo>b__0(Card c)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Hearthstone_Collection_Tracker.SetCardsManager.LoadSetsInfo(String collectionStoragePath)
   --- End of inner exception stack trace ---
   at Hearthstone_Collection_Tracker.SetCardsManager.LoadSetsInfo(String collectionStoragePath)
   at Hearthstone_Collection_Tracker.Internal.PluginSettings.SetActiveAccount(String accountName, Boolean forceReload)
   at Hearthstone_Collection_Tracker.Internal.PluginSettings.LoadSettings(String dataDir)
   at Hearthstone_Collection_Tracker.HearthstoneCollectionTrackerPlugin.OnLoad()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load()

Edit: I saw your post, you noticed it already after posting this. You might ignore this.

**Comment by CookieCompiler** [comment]
Obviously this was a bug in HDT 1.6.1 and 1.6.2. In HDT 1.6.3 this error is gone.
